Support sets of modules that don't have a module without priority
So far setup_environment_internal.py assumed exactly one module would
be without priority, and it would break on a set of modules that
doesn't any module without priority:

Traceback (most recent call last):
  File "sources/base/setup_environment_internal.py", line 571, in <module>
    load_modules()
  File "sources/base/setup_environment_internal.py", line 191, in load_modules
    execfile(module)
TypeError: must be string, not None

This change makes setup_environment_internal.py accept sets of modules
that don't contain any module without priority.

Change-Id: I0e4e2831304983e25f6b2a3e3ae84506502c336b
Signed-off-by: Mario Domenech Goulart <mario@ossystems.com.br>